package com.odisha.handloom.entity;

public enum OrderStatus {
    PENDING,
    CONFIRMED,
    SELLER_CONFIRMED,
    PACKED,
    READY_TO_SHIP,
    DISPATCHED,
    IN_TRANSIT,
    OUT_FOR_DELIVERY,
    DELIVERED,
    DELIVERY_FAILED,
    RETURN_REQUESTED,
    RETURNED,
    REPLACED,
    REPLACEMENT_REQUESTED,
    ORDER_CANCELLED_BY_SELLER,
    CANCELLED,
    RTO_INITIATED,
    RTO_COMPLETED,
    INVOICE_SENT,
    SHIPPED
}
