<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.odisha</groupId>
    <artifactId>odisha-handloom-microservices</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Odisha Handloom Microservices</name>
    <description>Aggregator for all Odisha Handloom Microservices</description>

    <modules>
        <module>OdishaHandLoomApplicationBackend/ServiceRegistry</module>
        <module>OdishaHandLoomApplicationBackend/ApiGateway</module>
        <module>OdishaHandLoomApplicationBackend/common-dto</module>
        <module>OdishaHandLoomApplicationBackend/IdentityService</module>
        <module>OdishaHandLoomApplicationBackend/ProductService</module>
        <module>OdishaHandLoomApplicationBackend/OrderService</module>
        <module>OdishaHandLoomApplicationBackend/SellerService</module>
        <module>OdishaHandLoomApplicationBackend/PaymentService</module>
        <module>OdishaHandLoomApplicationBackend/LogisticsService</module>
        <module>OdishaHandLoomApplicationBackend/NotificationService</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring-boot.version>3.4.1</spring-boot.version>
        <spring-cloud.version>2024.0.0</spring-cloud.version>
    </properties>
</project>