@echo off
echo Starting Microservices Architecture...

echo Starting Service Registry (Eureka)...
start "Service Registry" cmd /k "cd OdishaHandLoomApplicationBackend/ServiceRegistry && mvn spring-boot:run"

echo Waiting for Service Registry to initialize (20 seconds)...
timeout /t 60

echo Starting API Gateway...
start "API Gateway" cmd /k "cd OdishaHandLoomApplicationBackend/ApiGateway && mvn spring-boot:run"

echo Starting Notification Service...
start "Notification Service" cmd /k "cd OdishaHandLoomApplicationBackend/NotificationService && mvn spring-boot:run"

echo Starting Identity Service...
start "Identity Service" cmd /k "cd OdishaHandLoomApplicationBackend/IdentityService && mvn spring-boot:run"

echo Starting Product Service...
start "Product Service" cmd /k "cd OdishaHandLoomApplicationBackend/ProductService && mvn spring-boot:run"

echo Starting Order Service...
start "Order Service" cmd /k "cd OdishaHandLoomApplicationBackend/OrderService && mvn spring-boot:run"

echo Starting Seller Service...
start "Seller Service" cmd /k "cd OdishaHandLoomApplicationBackend/SellerService && mvn spring-boot:run"

echo Starting Payment Service...
start "Payment Service" cmd /k "cd OdishaHandLoomApplicationBackend/PaymentService && mvn spring-boot:run"

echo Starting Logistics Service...
start "Logistics Service" cmd /k "cd OdishaHandLoomApplicationBackend/LogisticsService && mvn spring-boot:run"

echo All services dispatched. Check individual console windows for logs.
pause
