package com.odisha.handloom.enums;

public enum ShipmentStatus {
    CREATED,
    ASSIGNED,
    PACKED,
    READY_TO_SHIP,
    DISPATCHED,
    IN_TRANSIT,
    OUT_FOR_DELIVERY,
    DELIVERED,
    DELIVERY_FAILED,
    RTO_INITIATED,
    RTO_COMPLETED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    PICKUP_INITIATED,
    PICKUP_COMPLETED,
    RETURN_IN_TRANSIT,
    RETURN_DELIVERED,
    REFUND_PROCESSED,
    COD_PENDING,
    COD_COLLECTED,
    COD_SETTLED
}
