package com.odisha.handloom;

import com.google.zxing.BinaryBitmap;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.odisha.handloom.service.LabelGenerationService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;

public class QrCodeVerificationTest {

    @Test
    public void testQrCodeGenerationAndDecoding() throws Exception {
        LabelGenerationService service = new LabelGenerationService();
        // Test with the strict format required by the user
        String payload = "UDRAKA|ORDER|ORD-VERIFY-123";

        System.out.println("Generating QR Code for payload: " + payload);

        // Generate
        byte[] qrBytes = service.generateQRCode(payload, 250, 250);

        Assertions.assertNotNull(qrBytes, "Generated bytes should not be null");
        Assertions.assertTrue(qrBytes.length > 0, "Generated bytes should not be empty");

        // Decode back to text to verify readability
        ByteArrayInputStream bis = new ByteArrayInputStream(qrBytes);
        BufferedImage validQrImage = ImageIO.read(bis);

        Assertions.assertNotNull(validQrImage, "Should be able to read bytes as Image");

        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(
                new BufferedImageLuminanceSource(validQrImage)));

        Result result = new MultiFormatReader().decode(binaryBitmap);

        // Verify content
        Assertions.assertEquals(payload, result.getText(), "Decoded QR text must match original payload");

        System.out.println("SUCCESS: QR Code generated and decoded correctly.");
        System.out.println("Decoded Text: " + result.getText());
    }
}
